---
version: '3.2'
services:
  redis:
    image: redis:alpine
    command: redis-server --appendonly yes
    volumes:
      - ./redis:/data

  server:
    build: ./
    image: scrumblr
    links:
    - redis
    ports:
    - '7000:8080'
#   volumes:
#     - .:/srv/scrumblr

#volumes:
#  redis:

